import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const chivo = Poppins({
  subsets: ["latin-ext"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es" className="scroll-smooth overflow-x-hidden">
      <body className={chivo.className}>{children}</body>
    </html>
  );
}
